// Static editorial guides and search metadata. Readable without JavaScript; FAQ <details> blocks also feed FAQPage schema.
const faq=(q,a)=>`<details class="faq"><summary>${q}</summary><p>${a}</p></details>`;
const section=(h,body,faqs=[])=>`<section class="content-section"><h2>${h}</h2>${body}${faqs.map(([q,a])=>faq(q,a)).join('')}</section>`;
const L=(href,text)=>`<a href="${href}">${text}</a>`;

const commonFaqs={
 works:['Will this text work on Instagram, TikTok and Discord?','Usually, in bios, captions, posts, comments and display names, because the result is ordinary Unicode text rather than a font. Usernames and handles normally allow only basic letters, numbers, periods and underscores, so styled letters are rejected there. Paste once and check the preview in the app before saving.'],
 boxes:['Why do some letters show as boxes or question marks?','The device viewing your text has no font containing that character. Newer phones rarely have this problem with the common styles, but older systems and some games do. Choose a widely supported style such as bold or italic when reach matters.'],
 a11y:['Can screen readers read fancy text?','Not reliably. Many screen readers announce each styled letter by its Unicode name or skip it, so a styled phrase can become hard to follow. Style a short accent, and keep important words, links and instructions in ordinary letters.'],
 free:['Is CopySprig free?','Yes. Every style and symbol is free, with no signup. Your text is transformed in your browser and never uploaded.'],
};

export const pageGuides={
 '':section('What is a fancy text generator?',`<p>A fancy text generator swaps ordinary letters for look-alike Unicode characters: mathematical bold and script letters, circled and squared letters, small capitals, and combining marks such as underlines and glitch effects. Because the result is text rather than a font file, you can paste it wherever plain text is accepted: an Instagram or TikTok bio, a Discord display name, a YouTube comment, or a game chat that supports Unicode.</p><h3>Popular styles</h3><p>${L('/bold-text/','Bold text')} and ${L('/italic-text/','italic text')} are the most widely supported. ${L('/cursive-text/','Cursive script')} and ${L('/gothic-text/','gothic blackletter')} add personality to a name. ${L('/bubble-text/','Bubble letters')}, ${L('/tiny-text/','tiny text')} and ${L('/glitch-text/','glitch text')} make playful accents. Want a mix? The ${L('/style-mixer/','style mixer')} layers a style, an effect and a symbol frame.</p><h3>Fonts for your favorite app</h3><p>See what works in each app, including character limits: ${L('/instagram-fonts/','Instagram fonts')}, ${L('/tiktok-fonts/','TikTok fonts')}, ${L('/discord-fonts/','Discord fonts')}, ${L('/twitter-fonts/','X (Twitter) fonts')} and ${L('/facebook-fonts/','Facebook fonts')}.</p>`,[commonFaqs.works,commonFaqs.boxes,commonFaqs.a11y,commonFaqs.free]),

 'bold-text':section('How to use bold text in a bio or post',`<p>Type your words above and click the Bold or Sans bold box. The copied result uses characters from Unicode’s Mathematical Alphanumeric Symbols block: 𝐀–𝐳 and 𝟎–𝟗. Serif bold (𝐁𝐨𝐥𝐝) looks classic; sans bold (𝗕𝗼𝗹𝗱) looks modern and reads well on phones.</p><h3>Good places for bold</h3><p>A display name, the first line of a bio, a section label in a long caption (“𝗛𝗼𝘂𝗿𝘀”, “𝗟𝗶𝗻𝗸𝘀”), or one key phrase in a post. Social apps that have no bold button, such as Instagram captions, LinkedIn posts and X posts, accept these characters as text.</p>`,[['Is this real bold formatting?','No. Each letter is replaced with a separate bold-looking Unicode character. That is why it survives copy and paste into apps without formatting tools, and why search inside those apps may not find the word.'],['Does bold text work on LinkedIn?','Yes, LinkedIn posts and headlines accept mathematical bold characters. Use it for a short heading only; long bold passages are hard to read and screen readers may announce each letter individually.'],commonFaqs.a11y]),

 'italic-text':section('Italic text you can paste anywhere',`<p>This page compares four slanted styles: serif italic (𝐼𝑡𝑎𝑙𝑖𝑐), bold italic (𝑰𝒕𝒂𝒍𝒊𝒄), sans italic (𝘐𝘵𝘢𝘭𝘪𝘤) and sans bold italic (𝙄𝙩𝙖𝙡𝙞𝙘). Unicode has no italic digits, so numbers stay plain.</p><h3>When to choose italic</h3><p>Italic suits quotes, book or song titles, a soft tagline, or emphasis in a caption where apps offer no formatting. Sans italic tends to look tidier beside the default font on most phones.</p>`,[['Why does the italic h look different?','Unicode reserves the italic h position for the existing Planck constant symbol ℎ. CopySprig uses that character so the word still looks complete.'],commonFaqs.works]),

 'cursive-text':section('Cursive and script letters for names',`<p>Script (𝒮𝒸𝓇𝒾𝓅𝓉) and bold script (𝓢𝓬𝓻𝓲𝓹𝓽) are the closest Unicode gets to handwriting. They are favorites for display names, bio headers and wedding or event captions.</p><h3>Tips for readable cursive</h3><p>Use it for a name or two or three words. Bold script holds up better at small sizes and in dark mode. Capital letters in script can look ornate, so try your phrase in both Title Case and lowercase before copying.</p>`,[['Why are some script capitals slightly different in style?','Several script capitals such as ℬ, ℰ and ℋ were encoded in Unicode earlier as letterlike symbols. CopySprig uses those official characters, so on some devices they come from a different font than their neighbors.'],['Is there a cursive font for Instagram?','Instagram does not offer font choices for bios, but it accepts these script characters as text. Copy your styled name here, paste it into the Name or Bio field, and preview it before saving.'],commonFaqs.boxes]),

 'gothic-text':section('Gothic, old English and blackletter text',`<p>Fraktur (𝔊𝔬𝔱𝔥𝔦𝔠) and bold Fraktur (𝕲𝖔𝖙𝖍𝖎𝖈) are often searched as old English, medieval or tattoo text. They suit gaming tags, metal and streetwear aesthetics, and dramatic headings.</p><h3>Legibility first</h3><p>Blackletter capitals can be hard to tell apart (𝔄, 𝔘 and 𝔑 look alike to many readers). Keep it to a short word, and try bold Fraktur for better contrast on a phone.</p>`,[['Is this the same as a tattoo font?','It looks similar, but it is Unicode text, not a font file. For a tattoo or print design, a designer should use a real blackletter typeface; this text is for pasting into apps.'],commonFaqs.a11y]),

 'double-struck-text':section('Double-struck (outline) letters',`<p>Double-struck letters (𝔻𝕠𝕦𝕓𝕝𝕖) come from mathematics, where ℝ and ℕ name number sets. They give a hollow, outline look that suits minimalist display names and headings, and they include digits 𝟘–𝟡.</p>`,[['Why do ℂ, ℍ, ℕ, ℙ, ℚ, ℝ and ℤ look slightly different?','Those capitals were encoded in Unicode before the rest of the alphabet, so a device may draw them from a different font. They are the correct characters.'],commonFaqs.works]),

 'bubble-text':section('Bubble letters: circled text to copy',`<p>Circled letters (Ⓑⓤⓑⓑⓛⓔ) and black bubble letters (🅑🅤🅑🅑🅛🅔) wrap each character in a circle. White bubbles support both cases and digits 0–20 as single characters; black bubbles are uppercase only.</p><h3>Making bubbles readable</h3><p>Bubble text is bold and playful, so it works best for one short word: a mood, a username accent or a sign-off. On some phones black bubbles render as emoji-sized glyphs.</p>`,[['Why did my lowercase letters turn uppercase?','Unicode only defines black (filled) circled letters in uppercase. CopySprig converts lowercase so the whole word stays in bubbles.'],commonFaqs.boxes]),

 'square-text':section('Square text and boxed letters',`<p>Squared letters (🄱🄾🅇) and black squares (🅱🅾🆇) frame each letter in a box, a popular look for gaming names and bold headers. Both sets are uppercase only and have no digits.</p>`,[['Why does 🅱 look like an emoji?','Some systems show certain black squared letters, such as 🅰 🅱 🅾 🅿, as emoji with color. That depends on the device and cannot be controlled by the text.'],commonFaqs.works]),

 'tiny-text':section('Tiny text: small caps, superscript and subscript',`<p>Tiny text uses three Unicode sets: small capitals (ᴛɪɴʏ), superscript (ᵗⁱⁿʸ) and subscript (ₜᵢₙᵧ, where available). Each covers a different set of letters, and CopySprig shows exactly which letters stay plain.</p><h3>Where tiny text shines</h3><p>Use it for a subtle aside in a bio, a soft caption, or a whisper-style comment. Superscript is great for footnote-style marks ¹²³.</p>`,[['Why are some letters not tiny?','Unicode does not include a complete small alphabet. Superscript q and subscript letters such as b, c, d and f do not exist, so those letters stay plain rather than being replaced by misleading look-alikes.'],commonFaqs.a11y]),

 'upside-down-text':section('Flip text upside down',`<p>The upside-down generator reverses each line and replaces lowercase letters with turned look-alikes: “hello” becomes “ollǝɥ”. It is a classic joke for comments, bios and messages.</p>`,[['Can I flip uppercase letters and numbers?','Only a few turned capitals and digits exist in Unicode, and many lack wide font support, so CopySprig keeps them plain for predictable results.'],['How do I flip text back?','Paste it into the generator above and flip it again, or use the reverse tool on the main generator. Plain-text recovery cannot undo the turned letters.']]),

 'glitch-text':section('Glitch, creepy and Zalgo text',`<p>Glitch text stacks combining marks above and below each letter: light glitch (g̷̓l̸̆i̶͂t̷̾c̸̈h̶̆) for a subtle crackle and heavy glitch for a full “Zalgo” effect. It is popular for horror, gaming and meme aesthetics.</p><h3>Use it sparingly</h3><p>Heavy glitch text can spill over neighboring lines and some apps strip or limit combining marks. It also adds many characters, so check character limits. CopySprig uses a fixed number of marks per letter so results stay predictable.</p>`,[['Is Zalgo text the same as glitch text?','Yes. Zalgo is the internet name for text covered in stacked combining diacritics. The heavy glitch style here is a controlled version.'],['Why did an app remove my glitch marks?','Some platforms limit or strip stacked combining characters to prevent layout abuse. Try the light glitch style instead.']]),

 'underline-text':section('Underline text without formatting tools',`<p>These styles add a combining mark under each character: single underline (u̲n̲d̲e̲r̲), double underline (u̳n̳d̳e̳r̳) and dotted underline. They work on plain letters or on styled letters from the ${L('/style-mixer/','style mixer')}.</p>`,[['Why does the underline look broken between letters?','Each letter carries its own line, so the font decides how closely they join. Most phones show a near-continuous line; some fonts leave small gaps.'],commonFaqs.works]),

 'small-caps':section('Small caps text',`<p>Small capitals (ꜱᴍᴀʟʟ ᴄᴀᴘꜱ) look like uppercase letters at lowercase height. They give a clean, editorial feel to names, headings and bios.</p>`,[['Why do Q and X stay normal?','Unicode has no standard small capital Q or X with dependable font support, so CopySprig leaves them plain rather than substituting unrelated characters.'],commonFaqs.a11y]),

 'fullwidth-text':section('Fullwidth vaporwave text',`<p>Fullwidth letters (ｖａｐｏｒｗａｖｅ) come from East Asian typography, where each Latin character fills a full square cell. Online they are known as vaporwave or aesthetic text.</p>`,[['Why are spaces narrow next to fullwidth letters?','CopySprig keeps your original spaces and punctuation. If you want a wider gap, add an extra space or use the Spaced style in the style mixer.'],commonFaqs.works]),

 'monospace-text':section('Monospace typewriter text',`<p>Monospace letters (𝚖𝚘𝚗𝚘𝚜𝚙𝚊𝚌𝚎) give a typewriter or code look to a name or caption, including digits 𝟶–𝟿. On Discord or GitHub, use real code formatting with backticks instead; it is more accessible.</p>`,[commonFaqs.works,commonFaqs.a11y]),

 'strikethrough-text':section('Strikethrough text for jokes and edits',`<p>Strikethrough adds a combining line through each character: s̶t̶r̶i̶k̶e̶. It is a favorite for self-correcting jokes (“I’m ̶t̶i̶r̶e̶d̶ fine”), sale prices and to-do lists in apps without formatting.</p>`,[['Does Discord need this?','Discord already supports ~~strikethrough~~ formatting in messages, which is more accessible. Use Unicode strikethrough in places without formatting, such as bios and display names.'],commonFaqs.works]),

 'style-mixer':section('Make a custom text style',`<p>The mixer combines three layers: a base style (for example bold script), an effect (underline, slash, light glitch) and a frame of symbols around each line. It is the fastest way to build a signature look for a display name or bio header.</p><h3>Keep combinations short</h3><p>Every effect adds combining characters, and frames add symbols, so the output count grows quickly. Watch the counter against your app’s limit.</p>`,[['Can I save my mix?','Yes. Tap the star to save the settings on this device. CopySprig saves the combination, never your words.'],commonFaqs.works]),

 'text-decorator':section('Decorate text with symbol frames',`<p>The decorator wraps each nonblank line in a matching pair of symbols: stars, hearts, flowers, brackets, moons, music notes and more. Pair it with plain text for readability, or with a style from the ${L('/style-mixer/','mixer')}.</p>`,[['Can I decorate several lines at once?','Yes. Each nonblank line gets its own frame, which is handy for multi-line bios.'],commonFaqs.works]),

 'plain-text':section('Convert fancy text back to normal text',`<p>Paste styled text and CopySprig maps supported Unicode letters back to ordinary A–Z, a–z and 0–9. It also removes combining underlines, strikes and glitch marks. Use it to make a styled name searchable, to fix text a form rejected, or to read text a screen reader struggled with.</p>`,[['Can every style be recovered?','Most letter styles can. Small caps, enclosed uppercase-only styles and alternating case lose the original capitalization, and upside-down text cannot be restored here.'],['Why does a form reject fancy text?','Many sign-up forms, usernames and payment fields only accept basic Latin letters. Recover plain text here and paste that instead.']]),

 'symbols':section('Find the right symbol fast',`<p>Every symbol has a plain-English name, so you can search for “outline heart”, “sparkle” or “arrow right” instead of scrolling. Browse by collection: ${L('/heart-symbols/','hearts')}, ${L('/star-symbols/','stars')}, ${L('/arrow-symbols/','arrows')}, ${L('/flower-symbols/','flowers')}, ${L('/moon-symbols/','moon and sky')}, ${L('/bracket-symbols/','brackets')}, ${L('/music-symbols/','music')}, ${L('/dividers/','dividers')} and ${L('/kaomoji/','kaomoji')}.</p>`,[['What is the difference between a text symbol and an emoji?','Text symbols such as ♡ and ☆ take the color and size of the surrounding text. Emoji such as 💜 and ✨ usually appear as colorful pictures. Some characters can display either way depending on the device.'],commonFaqs.boxes]),

 'arrow':section('Arrows for bios and link pointers',`<p>Arrows guide the eye: ↓ toward a link in your bio, → between steps, ↺ for “repeat”. Thin arrows (→) look clean beside text; heavy ones (➜, ➤) stand out more.</p>`,[['Which arrow points to my link in bio?','Downward arrows such as ↓ or ⇣ are the usual choice, placed on the last line of a bio right above the link.'],commonFaqs.boxes]),
 'flower':section('Flower symbols for soft aesthetics',`<p>Flower characters such as ✿, ❀ and ❁ add a gentle accent to names, captions and dividers. They are text symbols, so they match your text color, unlike flower emoji such as 🌸.</p>`,[['How do I make a flower divider?','Copy one flower and place it between short lines or dashes, like ── ✿ ──, or use a ready-made divider from the dividers collection.'],commonFaqs.boxes]),
 'moon':section('Moon, sun and sky symbols',`<p>Crescents (☾ ☽), suns (☀ ☼), clouds and stars build a celestial or night aesthetic for bios and captions. Pair a moon with a ${L('/star-symbols/','sparkle')} for a classic look: ☾ ⋆ ✧.</p>`,[commonFaqs.boxes]),
 'bracket':section('Decorative brackets and frames',`<p>Corner brackets 「」, lenticular brackets 【】 and angle quotes 《》 frame a word or label, like 【NEW】 or 「quote」. Many come from East Asian punctuation and look neat around short labels.</p>`,[['How do I frame a whole line?','Use the text decorator, which adds a matching pair of symbols around each line automatically.']]),
 'music':section('Music notes to copy and paste',`<p>Notes like ♪, ♫ and ♬ signal a song lyric, a playlist or a musician’s bio. Put a note before and after a song title: ♫ title ♫.</p>`,[commonFaqs.boxes]),
 'face':section('Kaomoji: Japanese text faces',`<p>Kaomoji are faces made from characters, read upright rather than sideways: (◕‿◕), (ᵔᴥᵔ), ¯\\_(ツ)_/¯. They add expression without an emoji keyboard and work almost anywhere text does.</p>`,[['Why does my kaomoji look misaligned?','Kaomoji mix characters from several scripts, and each app’s font sets their widths. The face may look slightly different after pasting; try a simpler one if it breaks.']]),
};

const platformBody=(app,facts,tips,faqs)=>section(`Fonts for ${app}: what works and where`,`<ul>${facts.map(f=>`<li>${f}</li>`).join('')}</ul><h3>Tips</h3><p>${tips}</p><p class="style-note">Limits are as published by ${app} at the time of writing and can change; the app’s own counter is final.</p>`,faqs);

export const platformPages=[
 {path:'instagram-fonts',label:'Instagram fonts',app:'Instagram',styleIds:['bold','sans-bold','script','bold-script','italic','fraktur','double-struck','small-caps','circled','fullwidth'],example:'Coffee & golden hour',
  intro:'Copy and paste fancy fonts for your Instagram bio, name and captions. Bold, cursive, small caps and more.',
  details:'Instagram has no font menu for bios or captions, but it accepts Unicode letters as text. Type once, copy a style, and paste it into Instagram.',
  use:'Style your name or the first line of your bio. Keep your handle, links and contact details in plain text.',
  guide:platformBody('Instagram',['<strong>Bio:</strong> up to 150 characters. Fancy letters often count as more than one character, so a styled bio fills up faster.','<strong>Name:</strong> up to 30 characters. It accepts styled letters and is searchable only in its plain form.','<strong>Username:</strong> letters, numbers, periods and underscores only. Fancy text will be rejected.','<strong>Captions, comments and Stories:</strong> styled text pastes fine; the Story editor’s own fonts are a separate option.'],`Pick one style per bio. Use ${L('/dividers/','short dividers')} and ${L('/symbols/','symbols')} for line breaks between sections. Check how it looks in both light and dark mode.`,[['Why does Instagram show my fancy name in search as normal?','Search and the username use plain characters. Your styled Name is a display label; people still find you by your handle.'],commonFaqs.boxes])},
 {path:'tiktok-fonts',label:'TikTok fonts',app:'TikTok',styleIds:['bold','sans-bold','bold-script','fraktur','bold-fraktur','circled','negative-circled','small-caps','glitch-light','fullwidth'],example:'daily vlogs',
  intro:'Fancy fonts for your TikTok bio, nickname and comments. Copy and paste bold, cursive, bubble and glitch text.',
  details:'TikTok accepts Unicode letters in bios, nicknames, captions and comments. Copy a style here and paste it into the app.',
  use:'Keep the bio short and scannable: one styled line plus a plain call to action works well.',
  guide:platformBody('TikTok',['<strong>Bio:</strong> up to 80 characters, so short styles such as bold or small caps fit best.','<strong>Name (nickname):</strong> up to 30 characters and accepts styled letters.','<strong>Username:</strong> letters, numbers, underscores and periods only.','<strong>Captions and comments:</strong> styled text pastes normally; heavy glitch text may be trimmed.'],`Glitch and bubble styles stand out in comments. In your bio, pair one styled word with a ${L('/arrow-symbols/','↓ arrow')} pointing at your link.`,[['Can I use fancy fonts in TikTok video text?','TikTok’s on-video text tool has its own fonts. You can paste Unicode styles into it, but the built-in fonts are usually easier to read.'],commonFaqs.works])},
 {path:'discord-fonts',label:'Discord fonts',app:'Discord',styleIds:['bold-script','fraktur','bold-fraktur','double-struck','small-caps','monospace','squared','negative-squared','superscript','glitch-heavy'],example:'night owl',
  intro:'Fancy fonts for your Discord display name, About Me and server names. Copy and paste gothic, script and boxed text.',
  details:'Discord display names, About Me sections, nicknames and server names accept Unicode letters. Copy a style here and paste it into Discord.',
  use:'Use a style for your display name or server nickname. For chat, Discord’s built-in formatting is easier to read.',
  guide:platformBody('Discord',['<strong>Username:</strong> lowercase letters, numbers, underscores and periods only. Fancy text is not allowed.','<strong>Display name and server nickname:</strong> up to 32 characters, and styled letters are accepted.','<strong>About Me:</strong> up to 190 characters.','<strong>Messages:</strong> Discord already has **bold**, *italic*, __underline__, ~~strikethrough~~ and `code` formatting, which screen readers handle better than Unicode styles.'],`Gothic and boxed styles are popular for gaming servers. Some servers set rules for readable nicknames, so moderators can mention you; check before switching.`,[['Why can’t people @mention my fancy nickname?','Typing a mention requires matching the characters. Others can still mention you by your plain username.'],commonFaqs.boxes])},
 {path:'twitter-fonts',label:'X (Twitter) fonts',app:'X',styleIds:['bold','sans-bold','italic','sans-italic','script','monospace','double-struck','small-caps','strikethrough','underline'],example:'Hot take incoming',
  intro:'Bold, italic and fancy fonts for X (Twitter) posts, bio and display name. Copy and paste Unicode text styles.',
  details:'X posts have no bold or italic button for most accounts, but they accept Unicode letters. Copy a style here and paste it into your post or profile.',
  use:'Bold a single phrase for emphasis or a thread heading. Keep hashtags and @mentions plain so they still link.',
  guide:platformBody('X',['<strong>Display name:</strong> up to 50 characters.','<strong>Bio:</strong> up to 160 characters.','<strong>Handle:</strong> letters, numbers and underscores only.','<strong>Posts:</strong> X counts many Unicode characters, including styled letters and emoji, as two characters toward the limit.'],`Styled hashtags do not work as hashtags, and styled words are harder to find in search. Bold one key phrase rather than a whole post.`,[['Does fancy text hurt my reach on X?','Styled words are not matched by search, and screen readers may spell them letter by letter. Use them for emphasis, not for the words you want people to find.'],commonFaqs.a11y])},
 {path:'facebook-fonts',label:'Facebook fonts',app:'Facebook',styleIds:['bold','sans-bold','italic','bold-script','double-struck','small-caps','circled','strikethrough','underline','fullwidth'],example:'Weekend market today',
  intro:'Bold, italic and fancy fonts for Facebook posts, comments and bios. Copy and paste Unicode text styles.',
  details:'Facebook posts, comments, Page descriptions and your Intro accept Unicode letters. Copy a style here and paste it into Facebook.',
  use:'Use bold for a post headline or event details, and keep phone numbers and links in plain text.',
  guide:platformBody('Facebook',['<strong>Profile name:</strong> Facebook’s name rules do not allow symbols or unusual characters, so styled names are usually rejected.','<strong>Intro (bio):</strong> up to 101 characters.','<strong>Posts and comments:</strong> styled letters paste normally.','<strong>Marketplace and groups:</strong> styled headings stand out, but plain keywords help people find your listing in search.'],`Bold makes a good headline for a long post. Pair it with ${L('/dividers/','a divider')} to break up sections.`,[['Why won’t Facebook let me use a fancy name?','Facebook requires names to use standard characters from a single language. Use styled text in posts and your Intro instead.'],commonFaqs.works])},
];

// Search titles: query-led, with a short styled sample (Unicode in titles helps them stand out).
export const seoTitles={
 '':'Fancy Text Generator: 𝓒𝓸𝓹𝔂 & 𝓟𝓪𝓼𝓽𝓮 34 Font Styles',
 'bold-text':'Bold Text Generator: Copy & Paste 𝐁𝐨𝐥𝐝 Font',
 'italic-text':'Italic Text Generator: Copy & Paste 𝘐𝘵𝘢𝘭𝘪𝘤 Font',
 'cursive-text':'Cursive Text Generator: Copy & Paste 𝓒𝓾𝓻𝓼𝓲𝓿𝓮 Font',
 'gothic-text':'Gothic & Old English Text Generator: 𝕮𝖔𝖕𝖞 & 𝕻𝖆𝖘𝖙𝖊',
 'double-struck-text':'Double-Struck Text Generator: 𝔻𝕠𝕦𝕓𝕝𝕖 Outline Letters',
 'bubble-text':'Bubble Text Generator: Copy & Paste Ⓑⓤⓑⓑⓛⓔ Letters',
 'square-text':'Square Text Generator: Copy & Paste 🅂🅀🅄🄰🅁🄴 Letters',
 'tiny-text':'Tiny Text Generator: Small ᵗᵉˣᵗ Copy & Paste',
 'upside-down-text':'Upside Down Text Generator: Flip ʇxǝʇ Online',
 'glitch-text':'Glitch Text Generator: Zalgo & Creepy G̷l̸i̶t̷c̸h̶ Text',
 'underline-text':'Underline Text Generator: Copy & Paste U̲n̲d̲e̲r̲l̲i̲n̲e̲',
 'small-caps':'Small Caps Generator: Copy & Paste ꜱᴍᴀʟʟ ᴄᴀᴘꜱ',
 'fullwidth-text':'Fullwidth Text Generator: Vaporwave ａｅｓｔｈｅｔｉｃ Text',
 'monospace-text':'Monospace Text Generator: Copy & Paste 𝚃𝚢𝚙𝚎𝚠𝚛𝚒𝚝𝚎𝚛 Font',
 'strikethrough-text':'Strikethrough Text Generator: Copy & Paste S̶t̶r̶i̶k̶e̶',
 'style-mixer':'Custom Font Style Mixer: Combine Fancy Text Styles',
 'text-decorator':'Text Decorator: Add ★ Symbol Frames ★ to Text',
 'plain-text':'Fancy Text to Normal Text Converter: Remove Unicode Fonts',
 'symbols':'Cool Symbols to Copy and Paste: ♡ ✦ ➜ ✿ ☾',
 'heart-symbols':'Heart Symbols ♡ ♥ ❤ Copy and Paste',
 'star-symbols':'Star & Sparkle Symbols ✦ ☆ ✧ Copy and Paste',
 'arrow-symbols':'Arrow Symbols → ➜ ↓ Copy and Paste',
 'flower-symbols':'Flower Symbols ✿ ❀ ❁ Copy and Paste',
 'moon-symbols':'Moon & Sky Symbols ☾ ☀ ⋆ Copy and Paste',
 'bracket-symbols':'Decorative Brackets 【】「」 Copy and Paste',
 'music-symbols':'Music Note Symbols ♪ ♫ ♬ Copy and Paste',
 'dividers':'Aesthetic Text Dividers ─ ✦ ─ for Bios: Copy and Paste',
 'kaomoji':'Kaomoji (◕‿◕) Japanese Text Faces: Copy and Paste',
 'instagram-fonts':'Instagram Fonts: Copy & Paste 𝓕𝓪𝓷𝓬𝔂 Bio Fonts',
 'tiktok-fonts':'TikTok Fonts: Copy & Paste 𝐅𝐚𝐧𝐜𝐲 Bio Text',
 'discord-fonts':'Discord Fonts: Fancy 𝕹𝖆𝖒𝖊 Text Copy & Paste',
 'twitter-fonts':'X (Twitter) Fonts: 𝗕𝗼𝗹𝗱 & 𝘐𝘵𝘢𝘭𝘪𝘤 Copy & Paste',
 'facebook-fonts':'Facebook Fonts: 𝗕𝗼𝗹𝗱 & Fancy Text Copy & Paste',
};
export const seoDescriptions={
 '':'Free fancy text generator. Type once and copy & paste 34 font styles: bold, cursive, bubble, gothic, tiny and glitch text for Instagram, TikTok, Discord and more. No signup.',
};
